// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEcsWRrDBMHUQ8zov6nwtITASANlfWdg4',
    appId: '1:491650075940:web:98e3bd0f84104881db77b1',
    messagingSenderId: '491650075940',
    projectId: 'mental-health-app-9ea02',
    authDomain: 'mental-health-app-9ea02.firebaseapp.com',
    storageBucket: 'mental-health-app-9ea02.appspot.com',
    measurementId: 'G-7VCE8QT6JS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqIQ-U1icNZdXqMrSQac1sTVkiIxdCiTQ',
    appId: '1:491650075940:android:9238f848b11b141cdb77b1',
    messagingSenderId: '491650075940',
    projectId: 'mental-health-app-9ea02',
    storageBucket: 'mental-health-app-9ea02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ7tur7TMmwF_xI19IIsq31aaMQMXDsns',
    appId: '1:491650075940:ios:63abaae5f6ccc6e6db77b1',
    messagingSenderId: '491650075940',
    projectId: 'mental-health-app-9ea02',
    storageBucket: 'mental-health-app-9ea02.appspot.com',
    iosBundleId: 'com.example.mentalhealthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ7tur7TMmwF_xI19IIsq31aaMQMXDsns',
    appId: '1:491650075940:ios:dc3da03f29156f97db77b1',
    messagingSenderId: '491650075940',
    projectId: 'mental-health-app-9ea02',
    storageBucket: 'mental-health-app-9ea02.appspot.com',
    iosBundleId: 'com.example.mentalhealthApp.RunnerTests',
  );
}
